# Despliegue para la aplicación canaria
apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-app
  labels:
    app: canary-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: canary-app
  template:
    metadata:
      labels:
        app: canary-app
    spec:
      containers:
      - name: canary-app
        image: francoriba/canary-app:latest  # Usa tu imagen aquí
        ports:
        - containerPort: 5001  # Puerto que expone la aplicación
---
# Servicio para la aplicación canaria
apiVersion: v1
kind: Service
metadata:
  name: canary-app
  labels:
    app: canary-app
spec:
  ports:
  - port: 80
    targetPort: 5001  # Mapea el puerto del servicio al puerto del contenedor
    protocol: TCP
    name: http
  selector:
    app: canary-app
